.TH "genoptStruct" 3 "Sat Sep 11 2010" "libgencurvefit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
genoptStruct \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long \fBdatapoints\fP"
.br
.ti -1c
.RI "double * \fBcoefs\fP"
.br
.ti -1c
.RI "const double * \fBydata\fP"
.br
.ti -1c
.RI "const double ** \fBxdata\fP"
.br
.ti -1c
.RI "const double * \fBedata\fP"
.br
.ti -1c
.RI "unsigned int \fBnumDataDims\fP"
.br
.ti -1c
.RI "double * \fBmodel\fP"
.br
.ti -1c
.RI "const unsigned int * \fBholdvector\fP"
.br
.ti -1c
.RI "double * \fBtemp_coefs\fP"
.br
.ti -1c
.RI "fitfunction \fBfitfun\fP"
.br
.ti -1c
.RI "costfunction \fBcostfun\fP"
.br
.ti -1c
.RI "updatefunction \fBupdatefun\fP"
.br
.ti -1c
.RI "unsigned int \fBupdatefrequency\fP"
.br
.ti -1c
.RI "unsigned int \fBnumvarparams\fP"
.br
.ti -1c
.RI "unsigned int \fBnumcoefs\fP"
.br
.ti -1c
.RI "unsigned int \fBpopsizeMultiplier\fP"
.br
.ti -1c
.RI "double \fBk_m\fP"
.br
.ti -1c
.RI "double \fBrecomb\fP"
.br
.ti -1c
.RI "double \fBtolerance\fP"
.br
.ti -1c
.RI "unsigned int \fBiterations\fP"
.br
.ti -1c
.RI "long \fBtotalpopsize\fP"
.br
.ti -1c
.RI "int \fBuseinitialguesses\fP"
.br
.ti -1c
.RI "unsigned int * \fBvarparams\fP"
.br
.ti -1c
.RI "double ** \fBgen_populationvector\fP"
.br
.ti -1c
.RI "double * \fBgen_trial\fP"
.br
.ti -1c
.RI "int \fBstrategy\fP"
.br
.ti -1c
.RI "double \fBMCtemp\fP"
.br
.ti -1c
.RI "double * \fBchi2Array\fP"
.br
.ti -1c
.RI "double \fBchi2\fP"
.br
.ti -1c
.RI "long \fBnumfititers\fP"
.br
.ti -1c
.RI "const double ** \fBlimits\fP"
.br
.ti -1c
.RI "void * \fBuserdata\fP"
.br
.ti -1c
.RI "struct \fBmt19937p\fP \fBmyMT19937\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for libgencurvefit from the source code.
