.TH "mt19937p" 3 "Sun Sep 12 2010" "libgencurvefit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mt19937p \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mt19937p.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned long \fBmt\fP [N]"
.br
.ti -1c
.RI "int \fBmti\fP"
.br
.ti -1c
.RI "unsigned long \fBmag01\fP [2]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned long \fBmag01\fP[2]"
.SS "unsigned long \fBmt\fP[N]"
.SS "int \fBmti\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for libgencurvefit from the source code.
