.TH "waveStats" 3 "Sat Sep 11 2010" "libgencurvefit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
waveStats \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBV_avg\fP"
.br
.ti -1c
.RI "double \fBV_stdev\fP"
.br
.ti -1c
.RI "long \fBV_maxloc\fP"
.br
.ti -1c
.RI "long \fBV_minloc\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for libgencurvefit from the source code.
